### ISSUE TITLE
Practical 2 homework mapping metro centres

### ISSUE THREAD

**Issue by cadooley** [andrewmaclachlan/CASA0005_homework#3]
It's not clear why this map of metro centres is included at the end. With the tmap_mode("plot") this means that this extra plot is just a map of the world metropolitan centres. Was the intention that metro centres get overlaid on top of the map of the exam data for the state? Also, to map these metro centres requires: data(metro) to be included in the code, otherwise there is an error saying 'metro' not found.

**Comment by andrewmaclachlan** [comment]
Ah yes, thanks. This might have just been an example of something i did in a session once. I have removed it. metro is data within the tmap package.
